baseURL = "https://www.arjobruijn.es"
languageCode = "en-us"
title = "Arjo Bruijnes"
theme = "kiss"
Paginate = 5
enableRobotsTXT = true
copyright = "&copy; Arjo Bruijnes 2021"

[params.taxonomies]
tag = "tags"
experience = "experience"
organization = "organizations"

[params.rss]
includeContent = true
authorName = "Arjo Bruijnes"
authorEmail = "arjo@weirdwater.net"

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
poweredBy = true
taxonomiesCount = true

[params.social]
twitter = "weirdwater"
github = "weirdwater"
instagram = "oreobrowness"
linkedin = "arjo-bruijnes-35924ba9"
rss = "index.xml"
email = "dev@arjobruijn.es"

[params.social.config]
platforms = ["github", "linkedin", "email", "rss"]

